### ISSUE TITLE
ModuleNotFoundError: No module named 'lama_cleaner'

### ISSUE THREAD

**Issue by anibalinbalin** [Uminosachi/sd-webui-inpaint-anything#97] opened 2023-09-20 17:01 UTC
Hey guys, I just installed the extension (I'm using google colab) and I dont have the tab. Checking the console I found:

*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
    ModuleNotFoundError: No module named 'lama_cleaner'

**Comment by Uminosachi** [comment] 2023-09-20 23:06
Are you adding the `--enable-insecure-extension-access` flag when starting the web UI?

Example:
```bash
!python launch.py --share --xformers --enable-insecure-extension-access
```

**Comment by Uminosachi** [comment] 2023-09-21 02:13
Duplicate of #88

**Comment by anibalinbalin** [comment] 2023-09-21 09:16
> Are you adding the `--enable-insecure-extension-access` flag when starting the web UI?
> 
> Example:
> 
> ```shell
> !python launch.py --share --xformers --enable-insecure-extension-access
> ```

Thanks for your reply. 
Yes, this is my line (that comes by default):
webui.py $share --api --disable-safe-unpickle --enable-insecure-extension-access --no-download-sd-model --no-half-vae  --ckpt "$model" --xformers $auth --disable-console-progressbars --upcast-sampling $ckptdir

I'm using the last ben google colab btw.

**Comment by Uminosachi** [comment] 2024-06-08 09:04
I have added the `lama_cleaner` package to this repository, so I am closing this issue.

**Closed by Uminosachi** 2024-06-08 09:04 UTC
