### ISSUE TITLE
Inpaint_anything incompatibility with other extensions. 

### ISSUE THREAD

**Issue by iaclaudioia8** [Uminosachi/sd-webui-inpaint-anything#112] opened 2023-10-28 10:39 UTC
Hi all,

I have figured out that when I install the extension for the first time it works properly, but when I restart the webui it does not load again, after trying to disable another extension that I have and enable just inpaint anything it works again :( 

Civitai Helper: Get Custom Model Folder
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
    ModuleNotFoundError: No module named 'lama_cleaner

**Comment by Uminosachi** [comment] 2023-10-28 11:09
Which other extension did you disable? I'll investigate the cause.

**Comment by iaclaudioia8** [comment] 2023-10-29 06:06
Sorry, i figured out now, that it had started work again because i have reinstalled the extension, i do not know why if i restart the WEBUI, extension stop to work, and give me the same output: 

*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
    ModuleNotFoundError: No module named 'lama_cleaner'

**Comment by Uminosachi** [comment] 2023-10-29 07:12
There's a possibility that the package is damaged. I recommend deleting the `venv` folder under stable-diffusion-webui and then starting webui.sh to reinstall the package from scratch.

**Comment by iaclaudioia8** [comment] 2023-10-31 06:59
Probably webuii automtic111 is not working properly, because i have installed more extension and i am getting the same issue:

*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 52, in <module>
        from functional import seq
    ModuleNotFoundError: No module named 'functional'

---
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
    ModuleNotFoundError: No module named 'lama_cleaner'
    
    
I have already informed @TheLasBen about it.

**Comment by Uminosachi** [comment] 2024-04-30 04:52
I have included lama_cleaner in the repository, so I am closing this issue.

**Closed by Uminosachi** 2024-04-30 04:52 UTC
