### ISSUE TITLE
lots of black regions in the segment anything image

### ISSUE THREAD

**Issue by deepfree3** [Uminosachi/sd-webui-inpaint-anything#67] opened 2023-07-01 08:19 UTC
In many cases, lots of black regions will be produced  in the segment anything image, and they will turn into masked regions in the mask image. This makes the mask image totally unusable.

**Comment by Uminosachi** [comment] 2023-07-01 09:08
Parts of the image that do not belong to any segment generated by the SAM will appear as black. Currently, I have made the black areas selectable, but I am considering an option to make them unselectable.

**Comment by Uminosachi** [comment] 2023-07-14 11:32
Duplicate of #66

**Comment by Uminosachi** [comment] 2023-07-14 11:36
I've implemented the `Anime Style (Up Detection, Down Mask Quality)` checkbox feature in the latest update. This helps with mask detection, especially in anime-style images, but may slightly decrease mask quality.

**Comment by Uminosachi** [comment] 2023-08-07 06:12
The `Anime Style (Up Detection, Down mask Quality)` checkbox and the `Ignore black area` checkbox have reduced the black area and made it unselectable. Therefore, this issue will be closed.

**Closed by Uminosachi** 2023-08-07 06:12 UTC
