### ISSUE TITLE
 why cant we use from the already installed inpainting  models 

### ISSUE THREAD

**Issue by sahil1572** [Uminosachi/sd-webui-inpaint-anything#55] opened 2023-06-18 08:04 UTC

**Comment by Uminosachi** [comment] 2023-06-18 09:04
You can use the installed inpainting model in the following way: Click the `Get mask` button on the `Mask only` tab, then click the `Send to img2img inpaint` button. This will send both the image and mask to img2img tab on the web UI.

Since some users might not have an inpainting model, direct execution has not been implemented.

**Comment by Uminosachi** [comment] 2023-06-19 03:40
In v1.9.0, I have added the function to search for inpainting models of the webUI and to display and run the Inpainting webui tab, if these models are found.

**Comment by Uminosachi** [comment] 2023-06-21 23:25
Duplicate of #33

**Comment by Uminosachi** [comment] 2023-08-07 05:05
The 'Inpainting webui' tab, which enables the use of the inpainting model saved in the web UI models directory, has been implemented. Therefore, this issue will be closed.

**Closed by Uminosachi** 2023-08-07 05:05 UTC
