### ISSUE TITLE
Impossible to get it showing up on the TABS, i already tried everything.

### ISSUE THREAD

**Issue by ZeroCool22** [Uminosachi/sd-webui-inpaint-anything#45] opened 2023-06-08 21:45 UTC
Already tried:

https://github.com/Uminosachi/sd-webui-inpaint-anything/issues/31

https://github.com/Uminosachi/sd-webui-inpaint-anything/issues/2

And no errors on the console:

```
venv "C:\Users\ZeroCool22\Desktop\Auto\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements
[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.



Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...



Launching Web UI with arguments: --xformers --api --vae-path C:\Users\ZeroCool22\Desktop\Auto\models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.ckpt
C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: llow is an invalid version and will not be supported in a future release
  warnings.warn(
python_server_full_path:  C:\Users\ZeroCool22\Desktop\Auto\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\ZeroCool22\Desktop\Auto\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
2023-06-08 18:39:00,086 - ControlNet - INFO - ControlNet v1.1.220
ControlNet preprocessor location: C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\annotator\downloads
2023-06-08 18:39:00,170 - ControlNet - INFO - ControlNet v1.1.220
Loading weights [c26f4c4227] from C:\Users\ZeroCool22\Desktop\Auto\models\Stable-diffusion\icbinpICantBelieveIts_v7.safetensors
Creating model from config: C:\Users\ZeroCool22\Desktop\Auto\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: C:\Users\ZeroCool22\Desktop\Auto\models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.ckpt
Applying optimization: xformers... done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.2s (import torch: 3.1s, import gradio: 0.8s, import ldm: 0.3s, other imports: 0.9s, load scripts: 1.9s, create ui: 3.7s, gradio launch: 0.1s).
Textual inversion embeddings loaded(4): bad-hands-5, bad-image-v2-39000, bad_prompt_version2, EasyNegative
Textual inversion embeddings skipped(3): nartfixer, nfixer, nrealfixer
Model loaded in 4.5s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 0.8s, apply half(): 1.0s, load VAE: 0.3s, move model to device: 0.6s, load textual inversion embeddings: 1.2s).
```

**AUTO's version:**

```
commit baf6946e06249c5af9851c60171692c44ef633e0 (HEAD -> master, tag: v1.3.2, origin/release_candidate, origin/master, origin/HEAD)
Merge: b6af0a38 6f754ab9
```

![Screenshot_2](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/13344308/452ba0aa-a2b4-410a-abc4-09b2c41c9d51)

![Screenshot_3](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/13344308/97e2f2ec-ef04-4f39-a349-2882710da5c6)

![Screenshot_5](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/13344308/e56bc381-17e4-4b61-a1ad-bd8ae4c58249)

**Comment by Uminosachi** [comment] 2023-06-09 00:04
I won't be able to identify the cause without some kind of clue from the log. Could you try deleting or moving the `venv` folder and then restarting the webui?

**Comment by fumatamax** [comment] 2023-06-19 09:23
Exactly the same thing happens to me. The tab does not appear at the top and neither in the settings.

**Comment by Uminosachi** [comment] 2023-06-21 23:09
Duplicate of #2

**Comment by Uminosachi** [comment] 2023-08-07 05:43
This issue is a duplicate of issue #58 and will be managed there; therefore, it will be closed.

**Closed by Uminosachi** 2023-08-07 05:43 UTC
