### ISSUE TITLE
Can't find the inpaint anything in my local webui

### ISSUE THREAD

**Issue by Dawsonlong** [Uminosachi/sd-webui-inpaint-anything#2] opened 2023-05-01 13:02 UTC
Dear

Firstly, thank you for your open source and sharing! I installed this extension on my local webui according to the instructions in the document, but after restarting the webui, I couldn't find it on my webui interface. I would like to ask what may be the cause of this

best wish

**Comment by Uminosachi** [comment] 2023-05-01 14:01
Isn't it displayed in the place where the tabs are arranged like the image below?

![5f56ad77-7a64-4fd5-a3c3-d08b6a2b6de7_resize](https://user-images.githubusercontent.com/49424133/235462261-10bf4895-b6b3-4473-8958-fab0c86e9041.png)

**Comment by qiaozhuoaqiaozhuo** [comment] 2023-05-05 10:02
Check your SD version, it's not work in old version in my PC too, then update resolved it.

**Comment by TheCompAce** [comment] 2023-05-30 00:36
I have my model set to SD2.1 do I need SD2.0 ?

**Comment by TheCompAce** [comment] 2023-05-30 01:05
That's what I thought. Thanks any way, I am just going to reinstall SD-WebUI from scratch. Thanks any way.

**Comment by Bellatrixie** [comment] 2023-05-30 17:37
Same problem. 
Looks like I actually fixed it, by going:
1. Settings -> User Interface -> Hidden UI tabs
2. Add to hidden UI tabs "Inpaint Anything" tab and reload UI. 
3. Go back to settings and remove "Inpaint Anything" tab from hidden UI's.

**Comment by TheCompAce** [comment] 2023-05-30 18:23
It's worked.. Thanks!!!

**Comment by shameforest** [comment] 2023-06-01 06:42
I have the same issue, but Bellatrixie's solution does not work for my, because I cannot type in "Inpaint Anything" in the field for "Hidden Tabs", I can only choose the tabs are already visible in the UI. But the UI does not show Inpaint Anything to begin with.

I am on a Runpod with "RunPod Stable Diffusion v1.5+v2".
I went to the extensions and installed from URL: https://github.com/Uminosachi/sd-webui-inpaint-anything.git
Then I looked for updates and reloaded the UI.
But there is no Inpaint Anything Tab. 
I tried this in two variations, one time I installed x-former, the other time I didn't. But that made no difference.

Any ideas what to do?

**Comment by Uminosachi** [comment] 2023-06-01 10:15
If the issue is due to some Python packages not being installed, a solution could be to activate the venv and install these packages individually.

For Windows:
```
.\venv\Scripts\activate
pip install xformers
pip install huggingface-hub
pip install diffusers
pip install segment-anything
pip install lama-cleaner
deactivate
```

For Linux:
```
source ./venv/bin/activate
pip install ...
deactivate
```

**Comment by shameforest** [comment] 2023-06-01 10:47
Unfortunately this didn't help. I still can't see the tab in the UI.

**Comment by shameforest** [comment] 2023-06-01 11:09
Okay, I think I fixed it, by restarting the pod/computer. Didn't know this was necessary. I thought restarting webui is enough.

**Comment by Uminosachi** [comment] 2023-08-07 05:42
This issue is a duplicate of issue #58 and will be managed there; therefore, it will be closed.

**Closed by Uminosachi** 2023-08-07 05:42 UTC

**Comment by Khampol** [comment] 2024-01-22 09:19
Extension > Available > (Load..) look for "Inpaint Anything TAB".

**Comment by eqxDev** [comment] 2024-02-17 19:25
> Extension > Available > (Load..) look for "Inpaint Anything TAB".

Fixed it for me thank you!!

**Comment by chandrasoekmawan** [comment] 2024-06-19 01:25
> Extension > Available > (Load..) look for "Inpaint Anything TAB".

Thanks,, it work for me.
